runtime: nodejs
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '20'

automatic_scaling:
  min_instances: 0
  max_instances: 0

includes:
- env.yaml

beta_settings:
  cloud_sql_instances: agile-binder-441009-r1:asia-southeast2:db-pg-binarkm7
