runtime: nodejs
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '21'

manual_scaling:
  instances: 1

includes:
- env.yaml

beta_settings:
  cloud_sql_instances: agile-binder-441009-r1:asia-southeast2:db-pg-binarkm7
